"""Data types for the Life Graph SDK.

Every public dataclass corresponds to a resource returned by the Life Graph
v1 API and includes a ``from_dict`` classmethod for convenient
deserialisation from JSON payloads.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


# ---------------------------------------------------------------------------
# Core memory types
# ---------------------------------------------------------------------------

@dataclass
class Memory:
    """A single memory stored in Life Graph.

    Attributes:
        id: Unique memory identifier.
        content: The textual content of the memory.
        tags: Classification tags attached to the memory.
        properties: Arbitrary key-value metadata.
        importance: Numeric importance score (0.0 – 1.0).
        confidence: Numeric confidence score (0.0 – 1.0).
        reasoning: Optional reasoning explanation for the memory.
        source_type: Origin of the memory (e.g. ``"ingest"``, ``"voice"``).
        status: Lifecycle status (e.g. ``"active"``, ``"superseded"``).
        created_at: ISO-8601 creation timestamp.
        updated_at: ISO-8601 last-update timestamp.
        access_count: Number of times this memory has been accessed.
    """

    id: str
    content: str
    tags: list[str] = field(default_factory=list)
    properties: dict = field(default_factory=dict)
    importance: float = 0.0
    confidence: float = 0.0
    reasoning: str | None = None
    source_type: str | None = None
    status: str | None = None
    created_at: str | None = None
    updated_at: str | None = None
    access_count: int = 0
    impact_score: float = 0.5

    @classmethod
    def from_dict(cls, data: dict) -> Memory:
        """Create a Memory from an API response dict.

        Args:
            data: A dict decoded from the API JSON payload.

        Returns:
            A fully-populated :class:`Memory` instance.
        """
        return cls(
            id=str(data.get("id", "")),
            content=data.get("content", ""),
            tags=data.get("tags", []),
            properties=data.get("properties", {}),
            importance=float(data.get("importance", 0.0)),
            confidence=float(data.get("confidence", 0.0)),
            reasoning=data.get("reasoning"),
            source_type=data.get("source_type"),
            status=data.get("status"),
            created_at=data.get("created_at"),
            updated_at=data.get("updated_at"),
            access_count=int(data.get("access_count", 0)),
            impact_score=float(data.get("impact_score", 0.5)),
        )


# ---------------------------------------------------------------------------
# Search types
# ---------------------------------------------------------------------------

@dataclass
class SearchResult:
    """A single search result from Life Graph.

    Attributes:
        content: Matched memory content.
        tags: Tags on the matching memory.
        score: Relevance score (higher is better).
        importance: Importance score of the memory.
        properties: Arbitrary metadata of the memory.
    """

    content: str
    tags: list[str] = field(default_factory=list)
    score: float | None = None
    importance: float = 0.0
    properties: dict = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: dict) -> SearchResult:
        """Create a SearchResult from an API response dict.

        Args:
            data: A dict decoded from the API JSON payload.

        Returns:
            A :class:`SearchResult` instance.
        """
        return cls(
            content=data.get("content", ""),
            tags=data.get("tags", []),
            score=data.get("score"),
            importance=float(data.get("importance", 0.0)),
            properties=data.get("properties", {}),
        )


@dataclass
class AskResult:
    """Result of an ``/ask`` query.

    Attributes:
        answer: Natural-language answer generated by the API.
        source_count: Number of source memories used to generate the answer.
        model: The model used for answer generation, if reported.
        memories: Backing memories used for the answer.
        query_time_ms: Time taken to process the query in milliseconds.
    """

    answer: str
    source_count: int = 0
    model: str | None = None
    memories: list[Memory] = field(default_factory=list)
    query_time_ms: float = 0.0

    @classmethod
    def from_dict(cls, data: dict) -> AskResult:
        """Create an AskResult from an API response dict.

        Args:
            data: A dict decoded from the API JSON payload.

        Returns:
            An :class:`AskResult` instance.
        """
        raw_memories = data.get("memories") or []
        return cls(
            answer=data.get("answer", ""),
            source_count=int(data.get("source_count", 0)),
            model=data.get("model"),
            memories=[Memory.from_dict(m) for m in raw_memories],
            query_time_ms=float(data.get("query_time_ms", 0.0)),
        )


@dataclass
class RecallContext:
    """Contextual recall bundle returned by the ``/recall`` endpoint.

    Attributes:
        relevant_memories: Memories relevant to the supplied context.
        decisions: Past decisions that may inform current action.
        intentions: Active intentions triggered by the context.
        warnings: Any warnings the system wants to surface.
    """

    relevant_memories: list[dict] = field(default_factory=list)
    decisions: list[dict] = field(default_factory=list)
    intentions: list[dict] = field(default_factory=list)
    warnings: list[dict] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: dict) -> RecallContext:
        """Create a RecallContext from an API response dict.

        Args:
            data: A dict decoded from the API JSON payload.

        Returns:
            A :class:`RecallContext` instance.
        """
        return cls(
            relevant_memories=data.get("relevant_memories", []),
            decisions=data.get("decisions", []),
            intentions=data.get("intentions", []),
            warnings=data.get("warnings", []),
        )


# ---------------------------------------------------------------------------
# Ingestion types
# ---------------------------------------------------------------------------

@dataclass
class IngestResult:
    """Result of a multi-modal ingestion operation.

    Attributes:
        memories_created: Number of memories created during ingestion.
        minio_key: Object-store key for the ingested asset.
        transcript: Transcribed text (voice ingestion).
        ocr_text: Extracted OCR text (image ingestion).
        text_length: Length of the extracted text in characters.
        chunks: Number of text chunks produced.
    """

    memories_created: int
    minio_key: str
    transcript: str | None = None
    ocr_text: str | None = None
    text_length: int | None = None
    chunks: int | None = None

    @classmethod
    def from_dict(cls, data: dict) -> IngestResult:
        """Create an IngestResult from an API response dict.

        Args:
            data: A dict decoded from the API JSON payload.

        Returns:
            An :class:`IngestResult` instance.
        """
        return cls(
            memories_created=int(data.get("memories_created", 0)),
            minio_key=data.get("minio_key", ""),
            transcript=data.get("transcript"),
            ocr_text=data.get("ocr_text"),
            text_length=data.get("text_length"),
            chunks=data.get("chunks"),
        )


# ---------------------------------------------------------------------------
# Graph types
# ---------------------------------------------------------------------------

@dataclass
class GraphEntity:
    """An entity in the knowledge graph.

    Attributes:
        name: Display name of the entity.
        label: Graph label (e.g. ``"Person"``, ``"Concept"``).
        properties: Arbitrary properties stored on the entity node.
    """

    name: str
    label: str | None = None
    properties: dict = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: dict) -> GraphEntity:
        """Create a GraphEntity from an API response dict.

        Args:
            data: A dict decoded from the API JSON payload.

        Returns:
            A :class:`GraphEntity` instance.
        """
        return cls(
            name=data.get("name", ""),
            label=data.get("label"),
            properties=data.get("properties", {}),
        )


@dataclass
class MemoryLink:
    """A typed link between two memories.

    Attributes:
        id: Unique link identifier.
        source_memory_id: UUID of the source memory.
        target_memory_id: UUID of the target memory.
        link_type: Relationship type (BECAUSE, EVIDENCED_BY, etc.).
        strength: Confidence/strength of the link (0.0–1.0).
        created_at: ISO-8601 creation timestamp.
    """

    id: str
    source_memory_id: str
    target_memory_id: str
    link_type: str
    strength: float = 0.5
    created_at: str | None = None

    @classmethod
    def from_dict(cls, data: dict) -> MemoryLink:
        """Create a MemoryLink from an API response dict.

        Args:
            data: A dict decoded from the API JSON payload.

        Returns:
            A :class:`MemoryLink` instance.
        """
        return cls(
            id=str(data.get("id", "")),
            source_memory_id=str(data.get("source_memory_id", "")),
            target_memory_id=str(data.get("target_memory_id", "")),
            link_type=data.get("link_type", ""),
            strength=float(data.get("strength", 0.5)),
            created_at=data.get("created_at"),
        )


# ---------------------------------------------------------------------------
# Session types
# ---------------------------------------------------------------------------

@dataclass
class Session:
    """A user interaction session tracked by Life Graph.

    Attributes:
        id: Unique session identifier.
        started_at: ISO-8601 timestamp when the session began.
        ended_at: ISO-8601 timestamp when the session ended, or ``None``.
        context: Arbitrary context dict associated with the session.
        summary: AI-generated summary of the session.
        memories_created: Number of memories created during the session.
        memories_accessed: Number of memories accessed during the session.
    """

    id: str
    started_at: str | None = None
    ended_at: str | None = None
    context: dict = field(default_factory=dict)
    summary: str | None = None
    memories_created: int = 0
    memories_accessed: int = 0
    outcome: str | None = None

    @classmethod
    def from_dict(cls, data: dict) -> Session:
        """Create a Session from an API response dict.

        Args:
            data: A dict decoded from the API JSON payload.

        Returns:
            A :class:`Session` instance.
        """
        return cls(
            id=str(data.get("id", "")),
            started_at=data.get("started_at"),
            ended_at=data.get("ended_at"),
            context=data.get("context") or {},
            summary=data.get("summary"),
            memories_created=int(data.get("memories_created", 0)),
            memories_accessed=int(data.get("memories_accessed", 0)),
            outcome=data.get("outcome"),
        )


# ---------------------------------------------------------------------------
# Intention types
# ---------------------------------------------------------------------------

@dataclass
class Intention:
    """A proactive intention stored in Life Graph.

    Attributes:
        id: Unique intention identifier.
        content: Human-readable description of the intention.
        trigger_type: Type of trigger (``"event"``, ``"time"``, etc.).
        trigger_condition: Condition that activates the intention.
        status: Current status (``"active"``, ``"completed"``, ``"dismissed"``).
        priority: Priority level (``"low"``, ``"normal"``, ``"high"``).
        created_at: ISO-8601 creation timestamp.
    """

    id: str
    content: str
    trigger_type: str = "event"
    trigger_condition: str | None = None
    status: str = "active"
    priority: str = "normal"
    created_at: str | None = None

    @classmethod
    def from_dict(cls, data: dict) -> Intention:
        """Create an Intention from an API response dict.

        Args:
            data: A dict decoded from the API JSON payload.

        Returns:
            An :class:`Intention` instance.
        """
        return cls(
            id=str(data.get("id", "")),
            content=data.get("content", ""),
            trigger_type=data.get("trigger_type", "event"),
            trigger_condition=data.get("trigger_condition"),
            status=data.get("status", "active"),
            priority=data.get("priority", "normal"),
            created_at=data.get("created_at"),
        )


# ---------------------------------------------------------------------------
# Identity / timeline types
# ---------------------------------------------------------------------------

@dataclass
class TimelineChapter:
    """A chapter in the identity timeline.

    Attributes:
        period: Human-readable period label (e.g. ``"2024-Q1"``).
        active: Memories that are currently active for the period.
        superseded: Memories that were superseded during the period.
    """

    period: str
    active: list[Memory] = field(default_factory=list)
    superseded: list[Memory] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: dict) -> TimelineChapter:
        """Create a TimelineChapter from an API response dict.

        Args:
            data: A dict decoded from the API JSON payload.

        Returns:
            A :class:`TimelineChapter` instance.
        """
        active_raw = data.get("active") or []
        superseded_raw = data.get("superseded") or []
        return cls(
            period=data.get("period", ""),
            active=[Memory.from_dict(m) for m in active_raw],
            superseded=[Memory.from_dict(m) for m in superseded_raw],
        )


@dataclass
class StaleBelief:
    """A belief that may be outdated.

    Attributes:
        memory: The memory representing the belief.
        prompt: Suggested question to challenge or refresh the belief.
        days_stale: Number of days since the belief was last confirmed.
    """

    memory: Memory
    prompt: str
    days_stale: int

    @classmethod
    def from_dict(cls, data: dict) -> StaleBelief:
        """Create a StaleBelief from an API response dict.

        Args:
            data: A dict decoded from the API JSON payload.

        Returns:
            A :class:`StaleBelief` instance.
        """
        return cls(
            memory=Memory.from_dict(data.get("memory") or {}),
            prompt=data.get("prompt", ""),
            days_stale=int(data.get("days_stale", 0)),
        )


# ---------------------------------------------------------------------------
# Knowledge gap types
# ---------------------------------------------------------------------------

@dataclass
class KnowledgeGap:
    """A detected gap in the user's knowledge base.

    Attributes:
        id: Unique identifier for the gap.
        topic: The topic or area the gap relates to.
        query_count: How many times users have asked about this gap.
        first_asked: ISO-8601 timestamp of the first relevant query.
        last_asked: ISO-8601 timestamp of the most recent query.
        resolved: Whether the gap has been resolved.
    """

    id: str
    topic: str
    query_count: int = 0
    first_asked: str | None = None
    last_asked: str | None = None
    resolved: bool = False

    @classmethod
    def from_dict(cls, data: dict) -> KnowledgeGap:
        """Create a KnowledgeGap from an API response dict.

        Args:
            data: A dict decoded from the API JSON payload.

        Returns:
            A :class:`KnowledgeGap` instance.
        """
        return cls(
            id=str(data.get("id", "")),
            topic=data.get("topic", ""),
            query_count=int(data.get("query_count", 0)),
            first_asked=data.get("first_asked"),
            last_asked=data.get("last_asked"),
            resolved=bool(data.get("resolved", False)),
        )


# ---------------------------------------------------------------------------
# Admin / job types
# ---------------------------------------------------------------------------

@dataclass
class Stats:
    """System statistics from Life Graph.

    Attributes:
        memory_count: Total number of stored memories.
        intention_count: Total number of intentions.
        gap_count: Total number of detected knowledge gaps.
        session_count: Total number of recorded sessions.
    """

    memory_count: int
    intention_count: int
    gap_count: int
    session_count: int

    @classmethod
    def from_dict(cls, data: dict) -> Stats:
        """Create a Stats from an API response dict.

        Args:
            data: A dict decoded from the API JSON payload.

        Returns:
            A :class:`Stats` instance.
        """
        return cls(
            memory_count=int(data.get("memory_count", 0)),
            intention_count=int(data.get("intention_count", 0)),
            gap_count=int(data.get("gap_count", 0)),
            session_count=int(data.get("session_count", 0)),
        )


@dataclass
class JobRun:
    """A background job execution record.

    Attributes:
        id: Unique job-run identifier.
        tenant_id: Tenant that owns the job run.
        job_name: Name of the job (e.g. ``"consolidation"``).
        status: Current status (``"queued"``, ``"running"``, ``"completed"``, ``"failed"``).
        started_at: ISO-8601 timestamp when the job started.
        completed_at: ISO-8601 timestamp when the job finished, or ``None``.
        error: Error message if the job failed, or ``None``.
        result: Arbitrary result payload from the job.
    """

    id: str
    tenant_id: str = ""
    job_name: str = ""
    status: str = "queued"
    started_at: str | None = None
    completed_at: str | None = None
    error: str | None = None
    result: dict = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: dict) -> JobRun:
        """Create a JobRun from an API response dict.

        Args:
            data: A dict decoded from the API JSON payload.

        Returns:
            A :class:`JobRun` instance.
        """
        return cls(
            id=str(data.get("id", "")),
            tenant_id=data.get("tenant_id", ""),
            job_name=data.get("job_name", ""),
            status=data.get("status", "queued"),
            started_at=data.get("started_at"),
            completed_at=data.get("completed_at"),
            error=data.get("error"),
            result=data.get("result") or {},
        )


# ---------------------------------------------------------------------------
# Rate-limit & envelope types
# ---------------------------------------------------------------------------

@dataclass
class RateLimitInfo:
    """Parsed rate-limit information from API response headers.

    Attributes:
        limit: Maximum requests allowed in the current window.
        remaining: Requests remaining in the current window.
        reset_at: Unix timestamp when the rate-limit window resets.
    """

    limit: int = 0
    remaining: int = 0
    reset_at: int = 0

    @classmethod
    def from_dict(cls, data: dict) -> RateLimitInfo:
        """Create a RateLimitInfo from a dict.

        Args:
            data: A dict with ``limit``, ``remaining``, and ``reset_at`` keys.

        Returns:
            A :class:`RateLimitInfo` instance.
        """
        return cls(
            limit=int(data.get("limit", 0)),
            remaining=int(data.get("remaining", 0)),
            reset_at=int(data.get("reset_at", 0)),
        )


@dataclass
class ApiResponse:
    """Generic wrapper matching the API's ``{"data": ..., "meta": {...}}`` envelope.

    Attributes:
        data: The unwrapped payload (any type).
        meta: Optional metadata dict returned alongside the payload.
    """

    data: Any = None
    meta: dict | None = None

    @classmethod
    def from_dict(cls, data: dict) -> ApiResponse:
        """Create an ApiResponse from a raw JSON dict.

        Args:
            data: The raw JSON dict from the API.

        Returns:
            An :class:`ApiResponse` instance.
        """
        return cls(
            data=data.get("data"),
            meta=data.get("meta"),
        )
